### ISSUE TITLE
LU decomposition returns wrong values

### ISSUE THREAD

**Issue by idiotWu** [BertrandBev/eigen-js#22]
## Problem

`eigen.Decompositions.lu()` returns wrong values which don't satisfy `LU = A`.

## Steps to Reproduce

Run the following code in demo page...

```js
const M = new eig.Matrix([[2, 1], [1, 4]]);
const lu = eig.Decompositions.lu(M);
return {...lu, "L*U": lu.L.matMul(lu.U)}
```

...and you will get:

![image](https://user-images.githubusercontent.com/6022672/122449104-75264b80-cfe0-11eb-8531-fc65806af7fe.png)

While the expected values are:

```
L = [[1, 0], [0.5, 1]],
U = [[2, 1], [0, 3.5]]
```

**Comment by idiotWu** [comment]
Just checked the [Eigen documentation for `FullPivLU`](https://eigen.tuxfamily.org/dox/classEigen_1_1FullPivLU.html) and found this method performs a decomposition for `A`, where `A = P^-1 * L * U  * Q^-1`.

Maybe it's better to change to following comment to match the original docs?

https://github.com/BertrandBev/eigen-js/blob/1aa37c8d1d61c83132091f8a4230ba8487b98839/src/classes/Decompositions.js#L20

**Comment by BertrandBev** [comment]
Good point. In practice, L is strictly lower triangular, which means that we need to add the identity matrix to complete the reconstruction

I will update the documentation to

> LU decomposition consists in decomposing a square matrix A as a product A = P^-1 * (L + I) * U * Q^-1
> Where U is upper triangular L lower triangular, I is the identity matrix, and P & Q are two permutation matrices

**Comment by BertrandBev** [comment]
Here we go!
https://bertrandbev.github.io/eigen-js/#/decompositions

**Comment by idiotWu** [comment]
Thanks!
