### ISSUE TITLE
One doubt about inverse of this case of matrix

### ISSUE THREAD

**Issue by lucaslgr** [BertrandBev/eigen-js#25]
As you can see below I've tried to inverse this matrix and the answer isn't compatible with Matlab answer. 
Do you know why the NaN (Not a number) appear in response?

EigenJS
![image](https://user-images.githubusercontent.com/30275723/133679395-cae00378-194b-4a2e-a0f0-997634d972f3.png)

Matlab
![image](https://user-images.githubusercontent.com/30275723/133679686-929d8bf3-5b29-43a7-a5bc-ff99cf8e002a.png)

**Comment by BertrandBev** [comment]
That's a good question! Have you tried in Eigen to see what it yields? Not sure it should have a sensible behaviour in the non invertible cases
