### ISSUE TITLE
No dist

### ISSUE THREAD

**Issue by obrhaberer** [BertrandBev/eigen-js#44]
Why didn't you include the eigen js you built in the repo?

**Comment by BertrandBev** [comment]
You're right, I'll do it!

**Comment by Archer6621** [comment]
> You're right, I'll do it!

Hello :) Any plans on fixing this? Right now when installing the module via `npm`/`yarn` it doesn't work straight out of the box, because it's missing files.

I suppose the alternative would be to build the project ourselves?

**Comment by BertrandBev** [comment]
@recidive done!

**Comment by recidive** [comment]
Thanks!
