### ISSUE TITLE
Proper way to use Garbage Collector

### ISSUE THREAD

**Issue by recidive** [BertrandBev/eigen-js#59]
Hello, I have this code for an Extended Kalman filter in TypeScript.

```typescript
import eigen from 'eigen'

export type NonLinearFunction = (x: eigen.Matrix) => eigen.Matrix
export type JacobianFunction = (x: eigen.Matrix) => eigen.Matrix

export class ExtendedKalmanFilter {
  private x: eigen.Matrix
  private P: eigen.Matrix
  private Q: eigen.Matrix
  private R: eigen.Matrix
  private f: NonLinearFunction
  private h: NonLinearFunction
  private Fj: JacobianFunction
  private Hj: JacobianFunction

  constructor(
    initialState: eigen.Matrix,
    initialCovariance: eigen.Matrix,
    processCovariance: eigen.Matrix,
    measurementCovariance: eigen.Matrix,
    stateTransition: NonLinearFunction,
    observation: NonLinearFunction,
    stateTransitionJacobian: JacobianFunction,
    observationJacobian: JacobianFunction,
  ) {
    this.x = initialState
    this.P = initialCovariance
    this.Q = processCovariance
    this.R = measurementCovariance
    this.f = stateTransition
    this.h = observation
    this.Fj = stateTransitionJacobian
    this.Hj = observationJacobian
  }

  predict(): void {
    this.x = this.f(this.x)
    const F = this.Fj(this.x)
    this.P = F.matMul(this.P).matMulSelf(F.transpose()).matAddSelf(this.Q)
  }

  update(z: eigen.Matrix): void {
    const y = z.matSub(this.h(this.x))
    const H = this.Hj(this.x)
    const S = H.matMul(this.P).matMulSelf(H.transpose()).matAddSelf(this.R)
    const K = this.P.matMul(H.transpose()).matMulSelf(S.inverse())

    this.x = this.x.matAdd(K.matMul(y))
    this.P = eigen.Matrix.identity(this.P.rows(), this.P.cols())
      .matSub(K.matMul(H))
      .matMul(this.P)
  }

  getState(): eigen.Matrix {
    return this.x
  }

  getCovariance(): eigen.Matrix {
    return this.P
  }
}
```

I'm having memory issues running this in Node.js.

What's the proper way to use GC in this case?

Thanks!

**Comment by BertrandBev** [comment]
Just like in the doc, you'll want to push exceptions for x & P in the constructor (which are not to be collected) 
`
eig.GC.pushException(x);
eig.GC.pushException(P);
`
And then after each iteration  (at the end of predict, update or both) run `eig.GC.flush();`

**Comment by recidive** [comment]
Yes, I tried that, it's not so simple, this gives me the error:

BindingError: Cannot pass deleted object as a pointer of type Matrix const*

And when I put the exceptions for both `x` and `P` in `predict` and `update` instead of just in the `constructor` it turns out deadly slow: ~2s for filter 1000 measurements in comparison to ~300ms using a pure JS implementation. When I don't use the GC it's like ~200ms but memory leaks, I'm not seeing a huge a advantage in using this due to thee hassle of dealing with this memory management.

Maybe my code needs a refactor to avoid creating anonymous matrices/replacing matrices with newly created matrices, something like that.
