### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by lawsonfulton** [BertrandBev/eigen-js#7]
Hey this looks like a great project! I have had a hard time finding something as powerful as Eigen for Javascript.

Do you have a list of features or roadmap you are working on?

**Comment by BertrandBev** [comment]
Thanks the the feedback! I don't really have much of a roadmap yet, besides maybe putting some work on the documentation, and adding typescript support down the line. Feel free to suggest what you think should be the next steps!

**Comment by zy6p** [comment]
This is a really great repository. I would use it a lot.   

Sometimes, the input and output of matrices seems to be a tedious process that requires nested for loops. Maybe using [Float64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array) is a good solution.
